import { readFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * The website's colours, held against the app's.
 *
 * They were different, and that was the point of noticing: somebody arriving
 * from a near-black site with a mint accent downloaded an app that is light by
 * default and teal, and it looked like a different company's.
 *
 * apps/web/src/tokens.css is generated by scripts/sync-palette.mjs from
 * apps/mobile/lib/theme.dart. This fails if somebody edits the palette and
 * forgets to run it, which is the only way the two can drift now.
 */

const ROOT = join(import.meta.dirname, '..', '..', '..')
const THEME = join(ROOT, 'apps', 'mobile', 'lib', 'theme.dart')
const TOKENS = join(ROOT, 'apps', 'web', 'src', 'tokens.css')

/** The Dart palette, parsed the same way the generator parses it. */
function dartPalette(name: string): Record<string, string> {
  const source = readFileSync(THEME, 'utf8')
  const start = source.indexOf(`static const ${name} = TrustIqPalette(`)
  const body = source.slice(start, source.indexOf(');', start))
  const out: Record<string, string> = {}
  for (const [, field, hex] of body.matchAll(/(\w+):\s*Color\(0x(FF[0-9A-Fa-f]{6})\)/g)) {
    // Destructured rather than indexed: a capture group is string | undefined
    // to the compiler even when the pattern guarantees it.
    if (field && hex) out[field] = '#' + hex.slice(2).toUpperCase()
  }
  return out
}

/** One CSS block's custom properties. */
function cssBlock(from: number): Record<string, string> {
  const css = readFileSync(TOKENS, 'utf8')
  const end = css.indexOf('}', from)
  const out: Record<string, string> = {}
  for (const [, name, hex] of css.slice(from, end).matchAll(/(--[\w-]+):\s*(#[0-9A-Fa-f]{6})\s*;/g)) {
    if (name && hex) out[name] = hex.toUpperCase()
  }
  return out
}

function lightTokens() {
  const css = readFileSync(TOKENS, 'utf8')
  return cssBlock(css.indexOf(':root {'))
}

function darkTokens() {
  const css = readFileSync(TOKENS, 'utf8')
  return cssBlock(css.indexOf(':root {', css.indexOf('@media (prefers-color-scheme: dark)')))
}

// Left is what the stylesheet calls it, right is the palette field it means.
const NAMES: Record<string, string> = {
  '--bg': 'ground',
  '--surface': 'surface',
  '--surface-elevated': 'surfaceSunken',
  '--border': 'rule',
  '--border-strong': 'ruleStrong',
  '--accent': 'accent',
  '--accent-dim': 'accentStrong',
  '--accent-soft': 'accentSoft',
  '--on-accent': 'onAccent',
  '--amber': 'caution',
  '--amber-soft': 'cautionSoft',
  '--coral': 'critical',
  '--coral-soft': 'criticalSoft',
  '--ok': 'ok',
  '--ok-soft': 'okSoft',
  '--text': 'ink',
  '--text-dim': 'inkSoft',
  '--text-faint': 'inkFaint',
}

describe('the site and the app are the same colours', () => {
  const cases: [string, Record<string, string>, Record<string, string>][] = [
    ['light', dartPalette('light'), lightTokens()],
    ['dark', dartPalette('dark'), darkTokens()],
  ]

  for (const [theme, dart, css] of cases) {
    it(`${theme}: every token matches the palette`, () => {
      const wrong: string[] = []
      for (const [name, field] of Object.entries(NAMES)) {
        if (css[name] !== dart[field]) {
          wrong.push(`${name} is ${css[name]}, ${field} is ${dart[field]}`)
        }
      }
      expect(wrong, `run: node scripts/sync-palette.mjs\n${wrong.join('\n')}`).toEqual([])
    })
  }

  it('the two themes are actually different', () => {
    // Without this, a generator that wrote the light palette into both blocks
    // would pass everything above on the light half and never be noticed.
    expect(lightTokens()['--bg']).not.toEqual(darkTokens()['--bg'])
    expect(lightTokens()['--text']).not.toEqual(darkTokens()['--text'])
  })

  it('nothing the site serves still names the old palette', () => {
    // The site's own colours before this: a near-black ground and a mint accent
    // that appears nowhere in the product.
    //
    // Stylesheets and the standalone pages together. This read App.css alone,
    // then every .css, and both times it missed the four hand-written pages in
    // public/ that carry their own styles — privacy, the deletion page and the
    // confirmation page sat on the old palette for days after the rest of the
    // site moved, and the check that existed to catch exactly that did not look
    // at them.
    const web = join(ROOT, 'apps', 'web')
    const files = [
      ...readdirSync(join(web, 'src')).filter((f) => f.endsWith('.css')).map((f) => join('src', f)),
      ...readdirSync(join(web, 'public')).filter((f) => f.endsWith('.html')).map((f) => join('public', f)),
    ]
    for (const file of files) {
      const text = readFileSync(join(web, file), 'utf8')
      for (const gone of ['#2DD4A7', '#060908', '#121C19', 'rgba(45, 212, 167']) {
        expect(text, `${gone} is left in ${file}`).not.toContain(gone)
      }
    }
  })

  it('the site is set in the same typeface as the app, everywhere', () => {
    // The colours were made to match and the lettering was not, which is the
    // same incoherence one layer up. Plex was picked for the app because its
    // Arabic companion is drawn to the same rhythm; a site in Inter throws that
    // away at the first impression.
    const dir = join(ROOT, 'apps', 'web')
    const files = [
      ...readdirSync(join(dir, 'src')).filter((f) => f.endsWith('.css')).map((f) => join('src', f)),
      ...readdirSync(dir).filter((f) => f.endsWith('.html')),
      ...readdirSync(join(dir, 'public')).filter((f) => f.endsWith('.html')).map((f) => join('public', f)),
    ]
    for (const file of files) {
      // Comments stripped first. The question is what the page asks a browser
      // for, not what a note in the source says about what it used to ask for,
      // and the note explaining this change is worth more than the shortcut.
      const text = readFileSync(join(dir, file), 'utf8')
        .replace(/\/\*[\s\S]*?\*\//g, '')
        .replace(/<!--[\s\S]*?-->/g, '')
      for (const gone of ['Space Grotesk', 'JetBrains Mono', "'Inter'"]) {
        expect(text, `${file} still asks for ${gone}`).not.toContain(gone)
      }
    }
  })
})
