import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

/**
 * The website's colours, held against the app's.
 *
 * They were different, and that was the point of noticing: somebody arriving
 * from a near-black site with a mint accent downloaded an app that is light by
 * default and teal, and it looked like a different company's.
 *
 * apps/web/src/tokens.css is generated by scripts/sync-palette.mjs from
 * apps/mobile/lib/theme.dart. This fails if somebody edits the palette and
 * forgets to run it, which is the only way the two can drift now.
 */

const ROOT = join(import.meta.dirname, '..', '..', '..')
const THEME = join(ROOT, 'apps', 'mobile', 'lib', 'theme.dart')
const TOKENS = join(ROOT, 'apps', 'web', 'src', 'tokens.css')

/** The Dart palette, parsed the same way the generator parses it. */
function dartPalette(name: string): Record<string, string> {
  const source = readFileSync(THEME, 'utf8')
  const start = source.indexOf(`static const ${name} = TrustIqPalette(`)
  const body = source.slice(start, source.indexOf(');', start))
  const out: Record<string, string> = {}
  for (const [, field, hex] of body.matchAll(/(\w+):\s*Color\(0x(FF[0-9A-Fa-f]{6})\)/g)) {
    // Destructured rather than indexed: a capture group is string | undefined
    // to the compiler even when the pattern guarantees it.
    if (field && hex) out[field] = '#' + hex.slice(2).toUpperCase()
  }
  return out
}

/** One CSS block's custom properties. */
function cssBlock(from: number): Record<string, string> {
  const css = readFileSync(TOKENS, 'utf8')
  const end = css.indexOf('}', from)
  const out: Record<string, string> = {}
  for (const [, name, hex] of css.slice(from, end).matchAll(/(--[\w-]+):\s*(#[0-9A-Fa-f]{6})\s*;/g)) {
    if (name && hex) out[name] = hex.toUpperCase()
  }
  return out
}

function lightTokens() {
  const css = readFileSync(TOKENS, 'utf8')
  return cssBlock(css.indexOf(':root {'))
}

function darkTokens() {
  const css = readFileSync(TOKENS, 'utf8')
  return cssBlock(css.indexOf(':root {', css.indexOf('@media (prefers-color-scheme: dark)')))
}

// Left is what the stylesheet calls it, right is the palette field it means.
const NAMES: Record<string, string> = {
  '--bg': 'ground',
  '--surface': 'surface',
  '--surface-elevated': 'surfaceSunken',
  '--border': 'rule',
  '--border-strong': 'ruleStrong',
  '--accent': 'accent',
  '--accent-dim': 'accentStrong',
  '--accent-soft': 'accentSoft',
  '--on-accent': 'onAccent',
  '--amber': 'caution',
  '--amber-soft': 'cautionSoft',
  '--coral': 'critical',
  '--coral-soft': 'criticalSoft',
  '--ok': 'ok',
  '--ok-soft': 'okSoft',
  '--text': 'ink',
  '--text-dim': 'inkSoft',
  '--text-faint': 'inkFaint',
}

describe('the site and the app are the same colours', () => {
  const cases: [string, Record<string, string>, Record<string, string>][] = [
    ['light', dartPalette('light'), lightTokens()],
    ['dark', dartPalette('dark'), darkTokens()],
  ]

  for (const [theme, dart, css] of cases) {
    it(`${theme}: every token matches the palette`, () => {
      const wrong: string[] = []
      for (const [name, field] of Object.entries(NAMES)) {
        if (css[name] !== dart[field]) {
          wrong.push(`${name} is ${css[name]}, ${field} is ${dart[field]}`)
        }
      }
      expect(wrong, `run: node scripts/sync-palette.mjs\n${wrong.join('\n')}`).toEqual([])
    })
  }

  it('the two themes are actually different', () => {
    // Without this, a generator that wrote the light palette into both blocks
    // would pass everything above on the light half and never be noticed.
    expect(lightTokens()['--bg']).not.toEqual(darkTokens()['--bg'])
    expect(lightTokens()['--text']).not.toEqual(darkTokens()['--text'])
  })

  it('nothing in the stylesheet still names the old palette', () => {
    // The site's own colours before this: a near-black ground and a mint accent
    // that appears nowhere in the product.
    const app = readFileSync(join(ROOT, 'apps', 'web', 'src', 'App.css'), 'utf8')
    for (const gone of ['#2DD4A7', '#060908', '#121C19', 'rgba(45, 212, 167']) {
      expect(app, `${gone} is left in App.css`).not.toContain(gone)
    }
  })
})
