#!/usr/bin/env bash
#
# Concatenates every migration, in filename order, into one file that can be
# pasted into the Supabase SQL editor in a single run.
#
#   ./scripts/bundle-migrations.sh
#
# Why this exists: applying migrations by hand means applying them in the right
# order, and the SQL editor does not enforce one. A schema that is missing 0007
# looks fine until a user picks their own evidence digest. One paste removes
# the ordering question entirely.
#
# Once the Supabase CLI is installed, `supabase db push` is the better route
# and this becomes unnecessary.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/supabase/all-migrations.sql"

{
  echo "-- TrustIQ schema, every migration in order."
  echo "-- Generated by scripts/bundle-migrations.sh. Do not edit by hand."
  echo "-- Paste the whole file into the Supabase SQL editor and run it once."
  echo "--"
  echo "-- Wrapped in a transaction: if any statement fails, nothing is applied,"
  echo "-- so a partial schema is not a state you can end up in."
  echo
  echo "begin;"
  echo

  for migration in "$ROOT"/supabase/migrations/*.sql; do
    name="$(basename "$migration")"
    echo
    echo "-- ==========================================================="
    echo "-- $name"
    echo "-- ==========================================================="
    echo
    cat "$migration"
    echo
  done

  echo
  echo "commit;"
} > "$OUT"

count=$(find "$ROOT/supabase/migrations" -name '*.sql' | wc -l | tr -d ' ')
lines=$(wc -l < "$OUT" | tr -d ' ')

echo "Bundled $count migrations into:"
echo "  $OUT"
echo "  ($lines lines)"
