/**
 * Writes the website's colours from the app's.
 *
 *   node scripts/sync-palette.mjs
 *
 * The site had a palette of its own: a near-black ground and a mint accent that
 * appears nowhere in the product. Two things were wrong with that. It did not
 * look like the app anybody would download, and it was dark only, while the app
 * has followed the system since it was written.
 *
 * So the values are read out of apps/mobile/lib/theme.dart rather than copied.
 * Copying twenty colours by hand is how the two drift, and a test asserts this
 * file was run after the palette last changed.
 *
 * The old variable names are kept as the names, so a thousand lines of App.css
 * did not have to be rewritten to change what they mean.
 */

import { readFileSync, writeFileSync } from 'node:fs'

const THEME = 'apps/mobile/lib/theme.dart'
const OUT = 'apps/web/src/tokens.css'

/** The two palettes, parsed out of the Dart rather than transcribed. */
function palette(name) {
  const source = readFileSync(THEME, 'utf8')
  const start = source.indexOf(`static const ${name} = TrustIqPalette(`)
  if (start === -1) throw new Error(`no ${name} palette in ${THEME}`)
  const body = source.slice(start, source.indexOf(');', start))

  const out = {}
  for (const m of body.matchAll(/(\w+):\s*Color\(0x(FF[0-9A-Fa-f]{6})\)/g)) {
    out[m[1]] = '#' + m[2].slice(2).toUpperCase()
  }
  return out
}

/**
 * What the stylesheet calls each colour.
 *
 * Left is the CSS name the site already uses, right is the palette field it now
 * means. Renaming the CSS instead would have touched every rule in App.css for
 * no gain: the point of this change is what the colours are, not what they are
 * called.
 */
const NAMES = {
  '--bg': 'ground',
  '--surface': 'surface',
  '--surface-elevated': 'surfaceSunken',
  '--border': 'rule',
  '--border-strong': 'ruleStrong',
  '--accent': 'accent',
  '--accent-dim': 'accentStrong',
  '--accent-soft': 'accentSoft',
  '--on-accent': 'onAccent',
  '--amber': 'caution',
  '--amber-soft': 'cautionSoft',
  '--coral': 'critical',
  '--coral-soft': 'criticalSoft',
  '--ok': 'ok',
  '--ok-soft': 'okSoft',
  '--text': 'ink',
  '--text-dim': 'inkSoft',
  '--text-faint': 'inkFaint',
}

function block(values, indent) {
  return Object.entries(NAMES)
    .map(([css, field]) => {
      if (!(field in values)) throw new Error(`palette has no ${field}`)
      return `${indent}${css}: ${values[field]};`
    })
    .join('\n')
}

const light = palette('light')
const dark = palette('dark')

const css = `/* Generated by scripts/sync-palette.mjs. Do not edit by hand.
 *
 * These are the app's colours, read out of apps/mobile/lib/theme.dart. The site
 * used to have a palette of its own — a near-black ground and a mint accent
 * that appears nowhere in the product — and somebody arriving from the website
 * would have downloaded an app that looked like a different company's.
 *
 * Light first, because the app is light first and follows the device. A trust
 * product opening bright white at midnight is its own small betrayal, and one
 * opening pitch black at noon is the same mistake pointing the other way.
 *
 * packages/core/src/palette-parity.test.ts fails if this file stops matching
 * the Dart it came from.
 */

:root {
${block(light, '  ')}

  --radius: 16px;
  --radius-sm: 12px;
}

@media (prefers-color-scheme: dark) {
  :root {
${block(dark, '    ')}
  }
}
`

writeFileSync(OUT, css)
console.log(`  ${Object.keys(NAMES).length} colours, two themes -> ${OUT}`)
