#!/usr/bin/env bash
#
# Copies the built domain packages into supabase/functions/_shared/ so Edge
# Functions can import them.
#
#   ./scripts/vendor-shared.sh
#
# Edge Functions are bundled from their own directory and cannot reach into an
# npm workspace, so the compiled output has to live alongside them. tsc already
# emits ESM with explicit .js extensions on relative imports, which is exactly
# what Deno wants; the bare specifiers (@trustiq/core and friends) are resolved
# by the import map in supabase/functions/deno.json.
#
# The output is generated and gitignored. Run this before deploying, or a
# function will ship against whatever the last build produced.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHARED="$ROOT/supabase/functions/_shared"

echo "Building the packages"
npm run build --prefix "$ROOT" >/dev/null

rm -rf "$SHARED"
mkdir -p "$SHARED"

for pkg in core ai server; do
  src="$ROOT/packages/$pkg/dist"
  if [ ! -d "$src" ]; then
    echo "error: $src does not exist; the build did not produce output for $pkg" >&2
    exit 1
  fi
  cp -r "$src" "$SHARED/$pkg"
  # Source maps point at paths that do not exist inside the function bundle and
  # only add weight to the deploy.
  find "$SHARED/$pkg" -name '*.map' -delete

  # Deno does not pick up a sibling .d.ts for a local .js import on its own, so
  # each file is pointed at its own declarations. Without this the functions
  # compile against untyped JavaScript: everything becomes `any`, and a typo in
  # a field name goes through unnoticed.
  while IFS= read -r js; do
    dts="$(basename "${js%.js}.d.ts")"
    [ -f "$(dirname "$js")/$dts" ] || continue
    printf '// @ts-self-types="./%s"
%s' "$dts" "$(cat "$js")" > "$js"
  done < <(find "$SHARED/$pkg" -name '*.js')
  echo "  vendored $pkg ($(find "$SHARED/$pkg" -name '*.js' | wc -l | tr -d ' ') files)"
done

cat > "$SHARED/README.md" <<'EOF'
Generated by scripts/vendor-shared.sh. Do not edit, and do not commit.

These are the compiled `packages/{core,ai,server}` outputs, copied here so
Supabase Edge Functions can import them. Change the sources, not these.
EOF

echo
echo "Vendored into supabase/functions/_shared/"
